project:
  output-dir: _output
  render:
    - data_ine.qmd
    - data_dgt.qmd

toc: true
toc-depth: 3
toc-location: right
number-sections: true

lang: es

format:
  html:
    theme: flatly
    embed-resources: true

execute:
  freeze: auto
